# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app.core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertalaboral',
            name='tipo_de_trabajo',
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='carga_horaria',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='posicion',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='profesion',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
